version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    build: .
    tty: true
    command: bash -c "python /opt/coinmena/manage.py migrate --noinput  && python /opt/coinmena/manage.py runserver 0.0.0.0:8000 --noreload"
#    command: bash -c "python /opt/coinmena/manage.py migrate --noinput  && python /opt/coinmena/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/opt/coinmena
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

